pipeline {
    agent any
    tools {
        nodejs 'node' // Nom configuré à l'étape 2.3
    }
    stages {
        stage('Install') {
            steps {
                bat 'npm install'
            }
        }
        stage('Build/Test') {
            steps {
                echo 'Simulation des tests...'
                // bat 'npm test' (si tu as des tests)
            }
        }
    }
}